Repository Online-Investment-Platform/Front_End, pull requests merged in 2024-12, with the labels that each got.

#27 feat: 거래 페이지 테이블 제작
  package.json
  src/app/search/[id]/layout.tsx
  src/app/search/[id]/page.tsx
  src/app/search/_components/stock-table.tsx
  src/app/search/layout.tsx
  src/app/search/page.tsx
  src/app/search/types/index.ts
  src/components/nav-bar/_components/nav-menu.tsx
  yarn.lock
Labels: 우선순위: MEDIUM, ✨ FEAT

#28 feat: 트레이딩차트 제작
  public/icons/Logo.svg
  public/icons/down-graph.svg
  public/icons/high-graph.svg
  src/app/globals.css
  src/app/main/_components/stock-card.tsx
  src/app/search/[id]/_components/candle-chart-container.tsx
  src/app/search/[id]/_components/candle-chart.tsx
  src/app/search/[id]/_components/loading-spiner.tsx
  src/app/search/[id]/_components/price-tooltip.tsx
  src/app/search/[id]/layout.tsx
  src/app/search/[id]/page.tsx
  src/app/search/[id]/types/index.ts
  src/app/search/layout.tsx
  src/app/search/page.tsx
  src/components/nav-bar/_components/nav-menu.tsx
Labels: 우선순위: MEDIUM, ✨ FEAT

#30 feat/29 : 검색기능 및 주식 차트 일부 수정
  src/app/main/_components/search-stock.tsx
  src/app/search/[id]/_components/candle-chart-container.tsx
  src/app/search/[id]/_components/candle-chart.tsx
  src/app/search/[id]/_components/stock-header.tsx
  src/app/search/[id]/page.tsx
  src/app/search/[id]/types/index.ts
  src/app/search/page.tsx
  src/hooks/index.ts
Labels: 우선순위: MEDIUM, ✨ FEAT

#32 refactor: 로그인 상태 관리 수정 및 토큰 갱신
  src/api/kospi-kosdac/index.ts
  src/app/layout.tsx
  src/app/main/_components/asset-info.tsx
  src/app/main/_components/skeleton.tsx
  src/app/main/_components/stock-carousel.tsx
  src/app/main/_components/stock-info.tsx
  src/app/page.tsx
  src/components/common/auth/refresh-modal.tsx
  src/components/common/modal/index.tsx
  src/components/nav-bar/_components/nav-menu.tsx
  src/hooks/use-auth.tsx
  src/hooks/use-token-refresh.ts
  src/store/.gitkeep
  src/store/modal-store.ts
  src/store/token-refresh.ts
  src/utils/auth-handler.tsx
  src/utils/next-cookies.ts
Labels: 🛠️ FIX, 우선순위: MEDIUM, ✨ FEAT

#38 refactor: 이거저거 리팩토링
  Netlify.toml
  public/images/logo-title.png
  public/logo.ico
  src/app/layout.tsx
  src/app/login/layout.tsx
  src/app/login/page.tsx
  src/app/main/_components/news-carousel.tsx
  src/app/members/layout.tsx
  src/app/members/page.tsx
  src/app/my-account/_components/stock-table.tsx
  src/app/my-account/page.tsx
  src/app/page.tsx
  src/app/provider.tsx
  src/components/common/auth/logo.tsx
  src/components/main-content.tsx
  src/components/nav-bar/index.tsx
  tailwind.config.ts
Labels: 우선순위: MEDIUM, ✨ FEAT

#46 refactor: 코드레빗에 리뷰 리팩토링
  src/api/news/index.ts
  src/api/ranking-table/index.ts
  src/app/not-found.tsx
  src/hooks/use-auth.ts
  src/validation/schema/auth/index.tsx
Labels: ✨ FEAT

#52 refactor: 로그인 연장 및 사이드바 정보수정
  src/api/side-Info/index.ts
  src/app/main/_components/stock-info.tsx
  src/hooks/use-token-refresh.ts
Labels: ✨ FEAT

#48 Feat/19: 거래하기 컴포넌트 제작
  public/icons/arrow-down.svg
  public/icons/arrow-right.svg
  src/api/transaction/index.ts
  src/app/main/_components/stock-card.tsx
  src/app/search/[id]/_components/candle-chart-container.tsx
  src/app/search/[id]/_components/price-tooltip.tsx
  src/app/search/[id]/_components/stock-header.tsx
  src/app/search/[id]/_components/transaction-form/edit-cancel.tsx
  src/app/search/[id]/_components/transaction-form/history.tsx
  src/app/search/[id]/_components/transaction-form/index.tsx
  src/app/search/[id]/_components/transaction-form/sell/index.tsx
  src/app/search/[id]/_components/transaction-form/trade/bidding.tsx
  src/app/search/[id]/_components/transaction-form/trade/buy-form-buttons.tsx
  src/app/search/[id]/_components/transaction-form/trade/buyable-quantity.tsx
  src/app/search/[id]/_components/transaction-form/trade/count-dropdown.tsx
  src/app/search/[id]/_components/transaction-form/trade/current-price.tsx
  src/app/search/[id]/_components/transaction-form/trade/index.tsx
  src/app/search/[id]/_components/transaction-form/trade/order-field.tsx
  src/app/search/[id]/_components/transaction-form/trade/price-type-dropdown.tsx
  src/app/search/[id]/_components/transaction-form/trade/total-amount.tsx
  src/app/search/[id]/_components/transaction-form/transaction-table.tsx
  src/app/search/[id]/page.tsx
  src/app/search/[id]/types/index.ts
  src/components/common/auth/refresh-modal.tsx
  src/components/common/button/index.tsx
  src/components/common/carousel/index.tsx
  src/components/common/check-button/index.stories.tsx
  src/components/common/check-button/index.tsx
  src/components/common/dropdown/custom-dropdown.tsx
  src/components/common/dropdown/index.stories.tsx
  src/components/common/dropdown/index.tsx
  src/components/common/input/index.tsx
  src/components/common/tabs/index.tsx
  src/components/common/toast/index.tsx
  src/context/stock-info-context.tsx
  src/hooks/use-escape-key.ts
  src/hooks/use-onclick-outside.ts
  src/utils/price.ts
  src/validation/schema/transaction-form/index.tsx
  tailwind.config.ts
  yarn.lock
Labels: ✨ FEAT

#58 feat: 포트폴리오 컴포넌트 제작
  package.json
  src/api/portfolio/index.ts
  src/app/main/_components/search-stock.tsx
  src/app/main/_components/stock-info.tsx
  src/app/portfolio/_components/portfoilo-card.tsx
  src/app/portfolio/constants/index.ts
  src/app/portfolio/layout.tsx
  src/app/portfolio/page.tsx
  src/app/portfolio/types/index.ts
  src/app/search/[id]/_components/transaction-form/trade/buy-form-buttons.tsx
  src/app/search/[id]/_components/transaction-form/trade/buyable-quantity.tsx
  src/components/nav-bar/_components/nav-menu.tsx
  yarn.lock
Labels: 우선순위: MEDIUM, ✨ FEAT

#60 refactor: 차트 컴포넌트 리팩토링
  src/api/candle-chart/index.ts
  src/api/portfolio/index.ts
  src/app/search/[id]/_components/candle-chart-container.tsx
  src/app/search/[id]/_components/candle-chart.tsx
  src/app/search/[id]/_components/price-tooltip.tsx
  src/app/search/[id]/_components/stock-header.tsx
  src/app/search/[id]/_components/transaction-form/index.tsx
  src/app/search/[id]/page.tsx
  src/app/search/page.tsx
  src/components/nav-bar/_components/nav-menu.tsx
  src/context/stock-info-context.tsx
Labels: ✨ FEAT

#62 Feat/57: 지정가 매수/매도 정정/취소 기능 구현
  src/api/transaction/index.ts
  src/app/search/[id]/_components/transaction-form/edit-cancel.tsx
  src/app/search/[id]/_components/transaction-form/edit-cancel/edit-table-body.tsx
  src/app/search/[id]/_components/transaction-form/edit-cancel/edit-table-header.tsx
  src/app/search/[id]/_components/transaction-form/edit-cancel/index.tsx
  src/app/search/[id]/_components/transaction-form/sell/index.tsx
  src/app/search/[id]/_components/transaction-form/trade/buy-form-buttons.tsx
  src/app/search/[id]/_components/transaction-form/trade/buyable-quantity.tsx
  src/app/search/[id]/_components/transaction-form/trade/index.tsx
  src/app/search/[id]/_components/transaction-form/trade/price-type-dropdown.tsx
  src/app/search/[id]/_components/transaction-form/transaction-table.tsx
  src/app/search/[id]/types/index.ts
Labels: ✨ FEAT

#63 Feat/56: 체결내역 불러오기
  public/images/green-wallet.png
  src/api/transaction/index.ts
  src/app/search/[id]/_components/transaction-form/edit-cancel/index.tsx
  src/app/search/[id]/_components/transaction-form/history.tsx
  src/app/search/[id]/_components/transaction-form/trade/index.tsx
  src/app/search/[id]/_components/transaction-form/transaction-table.tsx
Labels: ✨ FEAT

#65 feat: 메인페이지 에러바운더리 적용
  src/api/news/index.ts
  src/app/main/_components/news-card.tsx
  src/app/page.tsx
  src/components/common/dropdown/index.tsx
  src/components/common/error-boundary/index.tsx
Labels: 우선순위: MEDIUM, ✨ FEAT

#67 refactor: UI 리팩토링
  src/app/portfolio/_components/portfoilo-card.tsx
  src/app/portfolio/constants/index.ts
  src/app/portfolio/types/index.ts
  src/app/search/_components/stock-table.tsx
  src/components/common/dropdown/index.tsx
Labels: 우선순위: HIGH, 💄 DESIGN

#70 Fix/69: input 에러 해결
  src/app/search/[id]/_components/transaction-form/edit-cancel/index.tsx
  src/app/search/[id]/_components/transaction-form/trade/order-field.tsx
  src/app/search/[id]/_components/transaction-form/trade/total-amount.tsx
  src/components/common/dropdown/index.tsx
  src/components/common/input/index.tsx
  src/utils/price.ts
Labels: 🛠️ FIX, 우선순위: HIGH

#72 fix: 버그 수정
  public/og-image.png
  src/app/globals.css
  src/app/layout.tsx
  src/app/search/[id]/_components/transaction-form/trade/total-amount.tsx
  src/app/search/[id]/page.tsx
  src/components/auth-input/index.tsx
  src/components/common/dropdown/index.tsx
  src/components/common/input/index.tsx
  src/validation/schema/auth/index.tsx
  src/validation/schema/transaction-form/index.tsx
Labels: 🛠️ FIX, 우선순위: HIGH

#74 feat: 튜토리얼 페이지 제작
  src/app/layout.tsx
  src/app/search/[id]/_components/tutorial/constant/index.ts
  src/app/search/[id]/_components/tutorial/tutorial-container.tsx
  src/app/search/[id]/_components/tutorial/tutorial-modal.tsx
  src/app/search/[id]/_components/tutorial/types/index.ts
  src/app/search/[id]/page.tsx
  src/components/common/tutorial/_components/tutorial-container.tsx
  src/components/common/tutorial/_components/tutorial-contents.tsx
  src/components/common/tutorial/_components/tutorial-modal.tsx
  src/components/common/tutorial/constant/index.ts
  src/components/common/tutorial/types/index.ts
Labels: 우선순위: MEDIUM, ✨ FEAT

#76 Refactor/75: 코드래빗 리뷰 1차 반영
  src/api/.gitkeep
  src/api/make-api-request.ts
  src/api/transaction/index.ts
  src/app/search/[id]/_components/transaction-form/edit-cancel/edit-table-body.tsx
  src/app/search/[id]/_components/transaction-form/edit-cancel/edit-table-header.tsx
  src/app/search/[id]/_components/transaction-form/edit-cancel/index.tsx
  src/app/search/[id]/_components/transaction-form/index.tsx
  src/app/search/[id]/_components/transaction-form/trade/buy-form-buttons.tsx
  src/app/search/[id]/_components/transaction-form/trade/index.tsx
  src/app/search/[id]/_components/transaction-form/trade/order-field.tsx
  src/app/search/[id]/_components/transaction-form/transaction-table.tsx
  src/app/search/[id]/types/index.ts
  src/components/common/button/index.tsx
  src/components/common/tabs/index.tsx
  src/types/transaction/index.ts
  src/validation/schema/transaction-form/index.tsx
Labels: ♻️REFACTOR

#78 Fix/77: 쿼리키 추가
  src/app/search/[id]/_components/transaction-form/history.tsx
Labels: 🛠️ FIX

#81 refactor: 코드 분리 및 파일명 변경
  src/app/search/[id]/_components/order-stock/buy-and-sell/buyable-quantity.tsx
  src/app/search/[id]/_components/order-stock/buy-and-sell/current-price.tsx
  src/app/search/[id]/_components/order-stock/buy-and-sell/form-buttons.tsx
  src/app/search/[id]/_components/order-stock/buy-and-sell/index.tsx
  src/app/search/[id]/_components/order-stock/buy-and-sell/input-field.tsx
  src/app/search/[id]/_components/order-stock/buy-and-sell/number-dropdown.tsx
  src/app/search/[id]/_components/order-stock/buy-and-sell/price-type-dropdown.tsx
  src/app/search/[id]/_components/order-stock/buy-and-sell/total-amount.tsx
  src/app/search/[id]/_components/order-stock/edit-cancel/edit-table-row.tsx
  src/app/search/[id]/_components/order-stock/edit-cancel/edit-table.tsx
  src/app/search/[id]/_components/order-stock/edit-cancel/index.tsx
  src/app/search/[id]/_components/order-stock/index.tsx
  src/app/search/[id]/_components/order-stock/layout.tsx
  src/app/search/[id]/_components/order-stock/login-notice.tsx
  src/app/search/[id]/_components/order-stock/order-history/index.tsx
  src/app/search/[id]/_components/order-stock/trade-table.tsx
  src/app/search/[id]/_components/transaction-form/edit-cancel/edit-table-header.tsx
  src/app/search/[id]/_components/transaction-form/edit-cancel/index.tsx
  src/app/search/[id]/_components/transaction-form/index.tsx
  src/app/search/[id]/_components/transaction-form/trade/bidding.tsx
  src/app/search/[id]/_components/transaction-form/trade/buy-form-buttons.tsx
  src/app/search/[id]/_components/transaction-form/trade/index.tsx
  src/app/search/[id]/_components/transaction-form/transaction-table.tsx
  src/app/search/[id]/hooks/use-limit-order-data.ts
  src/app/search/[id]/hooks/use-limit-order-mutations.ts
  src/app/search/[id]/hooks/use-trade-mutations.ts
  src/app/search/[id]/page.tsx
  src/app/search/[id]/types/index.ts
  src/components/common/dropdown/index.tsx
  src/components/common/tabs/index.tsx
  src/constants/trade.ts
  tailwind.config.ts
Labels: ♻️REFACTOR

#84 feat: 기업상세정보 ui구현
  src/app/globals.css
  src/app/login/layout.tsx
  src/app/main/layout.tsx
  src/app/members/layout.tsx
  src/app/my-account/layout.tsx
  src/app/portfolio/layout.tsx
  src/app/search/[id]/_components/detail-info/company-overview/consensus.tsx
  src/app/search/[id]/_components/detail-info/company-overview/financial-statements.tsx
  src/app/search/[id]/_components/detail-info/company-overview/index.tsx
  src/app/search/[id]/_components/detail-info/company-overview/target-price.tsx
  src/app/search/[id]/_components/detail-info/index.tsx
  src/app/search/[id]/_components/detail-info/relative-news/index.tsx
  src/app/search/[id]/layout.tsx
  src/app/search/[id]/page.tsx
  src/app/search/layout.tsx
  src/components/nav-bar/_components/nav-menu.tsx
  tailwind.config.ts
Labels: ✨ FEAT
