Repository Online-Investment-Platform/Front_End, pull requests merged in 2025-01, with the labels that each got.

#90 feat: useAuth 중복수정
  src/app/error.tsx
  src/hooks/use-auth.ts
Labels: 우선순위: MEDIUM, ✨ FEAT

#89 feat: 기업정보 탭 api 연결
  package.json
  src/api/company-details/index.ts
  src/api/make-api-request.ts
  src/app/globals.css
  src/app/search/[id]/_components/candle-chart.tsx
  src/app/search/[id]/_components/detail-info/company-overview/consensus.tsx
  src/app/search/[id]/_components/detail-info/company-overview/financial-statements.tsx
  src/app/search/[id]/_components/detail-info/company-overview/index.tsx
  src/app/search/[id]/_components/detail-info/company-overview/target-price.tsx
  src/app/search/[id]/_components/detail-info/index.tsx
  src/app/search/[id]/_components/detail-info/relative-news/index.tsx
  src/app/search/[id]/_components/loading-spinner.tsx
  src/app/search/[id]/_components/order-stock/edit-cancel/index.tsx
  src/app/search/[id]/_components/order-stock/index.tsx
  src/app/search/[id]/_components/order-stock/order-history/index.tsx
  src/app/search/[id]/page.tsx
  src/constants/.gitkeep
  src/constants/company-details.ts
  src/context/stock-info-context.tsx
  src/types/.gitkeep
  src/types/company-details/index.ts
  src/utils/calculate-consensus.ts
  src/utils/clean-text.ts
  src/utils/price.ts
  tailwind.config.ts
  yarn.lock
Labels: ✨ FEAT

#92 fix: stockInfo가 null 일 수도 있는 문제에 대해 해결
  src/app/search/[id]/_components/order-stock/buy-and-sell/current-price.tsx
  src/app/search/[id]/_components/order-stock/buy-and-sell/index.tsx
  src/app/search/[id]/_components/order-stock/buy-and-sell/input-field.tsx
Labels: 🛠️ FIX

#94 design: 테일윈드 설정에 맞게 색상코드 설정
  src/app/main/_components/asset-info.tsx
  src/app/main/_components/flucctuate-table.tsx
  src/app/main/_components/ranking-stock.tsx
  src/app/main/_components/search-stock.tsx
  src/app/main/_components/skeleton.tsx
  src/app/main/_components/stock-card.tsx
  src/app/main/_components/stock-info.tsx
  src/app/my-account/layout.tsx
  src/app/portfolio/layout.tsx
  src/app/search/[id]/_components/order-stock/buy-and-sell/price-type-dropdown.tsx
  src/app/search/[id]/_components/tutorial/tutorial-modal.tsx
  src/app/search/[id]/layout.tsx
  src/app/search/_components/stock-table.tsx
  src/components/auth-input/index.tsx
  src/components/common/auth/refresh-modal.tsx
  src/components/common/button/index.tsx
  src/components/common/carousel/index.tsx
  src/components/common/dropdown/index.tsx
  src/components/common/input/index.tsx
  src/components/common/tabs/index.tsx
  src/components/common/tutorial/_components/tutorial-contents.tsx
  src/components/common/tutorial/_components/tutorial-modal.tsx
  src/components/nav-bar/_components/nav-icon-button.tsx
  src/components/nav-bar/_components/nav-menu.tsx
Labels: 우선순위: LOW, 💄 DESIGN
